### ISSUE TITLE
Table Alignment

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#102]
![image](https://github.com/user-attachments/assets/c8081c0b-c7c5-42f8-a8a5-86c9ac515e39)

To increase the readability of the numbers, I would align all columns except for the first one to the right:

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/56f369e8-df6d-49de-8296-e07d0efd17c7">

**Comment by samclassix** [comment]
<img width="1278" alt="Screenshot 2024-08-13 at 9 34 57 AM" src="https://github.com/user-attachments/assets/fda89d8b-dc86-447e-ad9f-7239f3890350">

- made the button narrower
- text of the last column before the action button would be next to the button.
- added a space on the left side of the action button
- 1st Column text-left
- All other column text-right
- Same in header 

<img width="1282" alt="Screenshot 2024-08-13 at 9 35 21 AM" src="https://github.com/user-attachments/assets/7c01ade7-8c19-4755-a3cd-4b374a3f54e2">

There is now a "gap" between the 1st and 2nd column.
- Move all table, excluding the 1st column and action column more to the left.

**Comment by samclassix** [comment]
considered done and closed
