### ISSUE TITLE
Support Version 2024 Savings

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#123]
TODO

**Comment by samclassix** [comment]
## Ecosystem/Ponder

- [x] Added `emit` in savings.sol
- [ ] Deploy new test version
- [x] Index Total Saved
- [x] Index Total Interest
- [x] Index Total Withdrawal

## Api

- [ ] Savings mapping saved
- [ ] Savings mapping interest
- [ ] Savings mapping withdraw
- [ ] Types and State

## App

#### State & Types

- [ ] Update to new Api Version
- [ ] Redux state import and fetch

#### UI
- [ ] Show total saved (global)
- [ ] Show total interest (global)
- [ ] Show total ZCHF distribution in Savings

- [ ] Show User Balance (real or implied)
- [ ] Show User Saved
- [ ] Show User Interest
- [ ] Show User Withdraw

- [ ] Action Save
- [ ] Action "Reinvest" (for accumulating)
- [ ] Action Claim (for claiming interest)
- [ ] Action Withdraw

- [ ] Table User, last 5 Saved entries
- [ ] Table User, last 5 Interest entries
- [ ] Table User, last 5 Withdraw entries

**Comment by luziusmeisser** [comment]
How about an UI along these lines?

![image](https://github.com/user-attachments/assets/2a5c1b84-78db-40df-ad4d-1d3ec482cf59)

**Comment by luziusmeisser** [comment]
Next iteration, "Save/Withdraw" like before:

![image](https://github.com/user-attachments/assets/059b3b05-930c-4682-9c41-7d753ca12a24)

But the global information is shown on top in a bar as @samclassix suggested. With the box next to the Save/Withdraw box indicating the outcome of the transaction, similar to when adjusting a position.

**Comment by luziusmeisser** [comment]
Concept would be as follows:

Stats area: shows global variables, total saved, interest rate, share of supply

Save area: allows the user to specify how much he wants to have in the savings account. Reducing the value leads to a withdrawal, increasing it to a deposit. The button should indicate how much is being withdrawn or deposited: for example, if the user balance is 13'500 ZCHF and the user already has 120'000 ZCHF saved, setting the saved amount to 10'000 ZCHF could make the button show "Save 10'000 ZCHF". Whereas in case of a withdrawal, the button label could be "Withdraw 3'500 ZCHF" or so. If there is no change and no accrued interest, the button should just say "Save". If there is no change but accrued interest, the button should say "Collect Accrued Interest".

Outcome area: in this area, the user sees the outcome of the transaction that can be done in the save area, starting with the currently saved balance and ending with the anticipated ending balance after the potential transaction.

**Comment by luziusmeisser** [comment]
One open question is where to indicate the lockup period. Not sure yet about that.

**Comment by samclassix** [comment]
> One open question is where to indicate the lockup period. Not sure yet about that.

I would suggest to add a note under the outcome values. Similar to the notification when a position is still in cooldown

**Comment by luziusmeisser** [comment]
> > One open question is where to indicate the lockup period. Not sure yet about that.
> 
> I would suggest to add a note under the outcome values. Similar to the notification when a position is still in cooldown

agree, that makes sense

**Comment by samclassix** [comment]
*UI only

<img width="1239" alt="Screenshot 2024-11-04 at 10 11 20 AM" src="https://github.com/user-attachments/assets/9efe83b2-f236-4fc4-b1c7-6fc0f9dfed7a">

<img width="1194" alt="Screenshot 2024-11-04 at 10 11 30 AM" src="https://github.com/user-attachments/assets/7fbcbbdc-c010-49e8-b4d6-3909b7011b2d">

**Comment by samclassix** [comment]
<img width="1108" alt="Screenshot 2024-11-05 at 9 41 45 AM" src="https://github.com/user-attachments/assets/84fce56b-de46-4b7a-9128-aa177065959f">

<img width="1096" alt="Screenshot 2024-11-05 at 9 42 15 AM" src="https://github.com/user-attachments/assets/a98b2bb2-ee10-48cc-9cf9-feeb5189e4fb">

**Comment by samclassix** [comment]
Considered in final testing and final improvements.
