### ISSUE TITLE
Support version 2024 interest rate governance

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#124]
Here's a first sketch:

![image](https://github.com/user-attachments/assets/73ee2de8-f030-452f-b2f9-f5aa0ee72056)

It should be embedded in the governance page and allow the users to propose an interest rate change, to veto proposals, and to enact proposals.

**Comment by samclassix** [comment]
# Propose Rate 

## action
<img width="1283" alt="Screenshot 2024-10-23 at 2 22 57 PM" src="https://github.com/user-attachments/assets/ae3123e1-36aa-4248-a422-d11ae3049c63">

## after
<img width="1141" alt="Screenshot 2024-10-23 at 2 23 25 PM" src="https://github.com/user-attachments/assets/cea60695-30da-4d98-93b7-36dc06bb7750">

# Denying Rate

## action
<img width="1299" alt="Screenshot 2024-10-23 at 2 26 47 PM" src="https://github.com/user-attachments/assets/0f675f44-a9f2-4343-94f8-2f424f8bd1f9">

## after
<img width="1240" alt="Screenshot 2024-10-23 at 2 27 24 PM" src="https://github.com/user-attachments/assets/703d5690-9550-4436-b949-2110933e922a">

# Applying Rate

## action
<img width="1316" alt="Screenshot 2024-10-23 at 2 17 32 PM" src="https://github.com/user-attachments/assets/8ebccbf0-9e7b-4857-a44e-b5d480351678">

## after
<img width="1166" alt="Screenshot 2024-10-23 at 2 22 33 PM" src="https://github.com/user-attachments/assets/6c2d9db1-9fca-4d87-9183-bfdd425af0ff">

**Comment by samclassix** [comment]
considered done.

**Comment by luziusmeisser** [comment]
Ich würde die current rate und das Benutzer-Proposal auf zwei Zeilen verteilen und dem Benutzerproposal ein label "New proposal:" geben. Dann das Textfeld und dahinter der Button.

Current rate braucht keinen dunkelgrauen Rahmen. Man kann damit ja nicht interagieren.

Beim Titel würde ich einfach "Leadrate" nehmen und nicht "Leadrate Proposals".

Anstatt "passed" würde ich "ready" schreiben. Erst wenn "Apply" gemacht wurde, ist "passed" korrekt.

**Comment by samclassix** [comment]
applied and considered closed.
