### ISSUE TITLE
Price indication wrong

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#129]
![image](https://github.com/user-attachments/assets/0bda4d28-a4fc-4749-b517-d33797d41c6b)

**Comment by luziusmeisser** [comment]
This was the price on chain at that time:

![image](https://github.com/user-attachments/assets/02ed36fc-7a53-4768-8c4c-a403a767c589)

**Comment by luziusmeisser** [comment]
Relaoding the page corrected the amount to  20'000, but not the price:

![image](https://github.com/user-attachments/assets/4f24dd03-7a62-4534-8923-4f5365c7dfc8)

**Comment by luziusmeisser** [comment]
Here, a little later, I noticed that the "challenged" indication is also wrong, it showed 50% when it was at 20%, and it showed 100% when it was at 60%:

![image](https://github.com/user-attachments/assets/47b80f0e-b60e-4b4e-a766-194760192622)

**Comment by luziusmeisser** [comment]
Doing the last round of challenges, I again notice the wrong price also here:

![image](https://github.com/user-attachments/assets/b5567b1c-4e28-4fdc-8ca9-1f509d79ee32)

**Comment by samclassix** [comment]
yes, i would assume its the latency between front and backend services. I will move fetching of the auction price to the app's responsibility.
