### ISSUE TITLE
Wrong phase indication on auction

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#131]
When looking at the pending auctions, the phase can be wrongly indicated as "zero phase" when in fact it is in the declining price phase:

![image](https://github.com/user-attachments/assets/0c98fe88-cc22-4301-bb7a-75cdba986eca)

The problem is here:

![image](https://github.com/user-attachments/assets/5f4c02dc-eb6a-4217-8c02-ce31c58a63c5)

The calculation is based on the maturity of the position instead of the challenge phase change time.

**Comment by samclassix** [comment]
It seams like expired positions got this issue, meaning expired positions are worthless. However, a auction before expiration will make the auction worthless at expiration. But not auctions started after expiration. 

Will go through all repos, it might be mixed up in the App but i will also check the backend services. 

Other thing is, that the App will always adjust unix timestamp to its local time, however, everything backend services related will use the server's local time. You will see this when you receive an alert (via telegram). Dates and times are not adjusted to your local time.  

But you can always retrieve the backend status with the telegram bot, query for `/help`

![Screenshot 2024-11-11 at 10 27 25 AM](https://github.com/user-attachments/assets/55024421-3528-4873-85d2-7678328868f8)

**Comment by samclassix** [comment]
Improvements applied, considered done.
