### ISSUE TITLE
Rejecting the bid transaction leads to runtime error

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#132]
When the user is about to bid:

![image](https://github.com/user-attachments/assets/26512ec5-0211-4c2d-846f-d337fc9adb84)

But then rejects the transaction, there is a runtime error and the browser navigates away to the mypositions page:

![image](https://github.com/user-attachments/assets/b9204afe-a8bc-4e28-bfb1-74060e75df92)

Correct behavior would be to stay on the page so the user can try again. The navigation should only happen after a successful bid.

**Comment by samclassix** [comment]
considered done.
