### ISSUE TITLE
Remove sentence with missing data from docs.

### ISSUE THREAD

**Issue by johanneskern** [Frankencoin-ZCHF/frankencoin-dapp#134]
On [https://docs.frankencoin.com/#store-of-wealth] I'd remove the phrase "Over the past fifty years it has lost XX% of its value, whereas the dollar and the euro have lost more than YY%." or replace it with some proper data which is not necessarily trivial. Lost it's value against what? A basket of goods? Gold?

**Comment by samclassix** [comment]
thanks for your input. :)

## Issues moved
https://github.com/Frankencoin-ZCHF/gitbook/issues/3
