### ISSUE TITLE
Values on savings page inconsistent

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#136]
<img width="849" alt="image" src="https://github.com/user-attachments/assets/51bcd8f6-f6ee-4200-8150-29e57df075ea">

When clicking on "max", I would expect the two values to be exactly the same, but they are not and I don't understand why.

**Comment by luziusmeisser** [comment]
I think the lower value might get live updates, but the upper value does not.

**Comment by samclassix** [comment]
No changes needed, considered closed.

**Comment by luziusmeisser** [comment]
Sorry, you are right, no change required.
