### ISSUE TITLE
Issue after launching challenge

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#138]
![image](https://github.com/user-attachments/assets/44cdfcba-0820-4973-9815-1f7a203f5890)

**Comment by luziusmeisser** [comment]
A minute later it was fine

**Comment by samclassix** [comment]
<img width="680" alt="Screenshot 2024-11-20 at 10 39 31 AM" src="https://github.com/user-attachments/assets/e428f322-a908-49f1-9a64-2a6258b39f90">

**Comment by samclassix** [comment]
Considered done.
Commit 4d753c7

- shows pending state

> ## What do you think? It works pretty good
> <img alt="Screenshot 2024-11-20 at 10 32 57 AM" width="1151" src="https://private-user-images.githubusercontent.com/96245183/388032895-5ffc1389-2f64-46d3-b720-2055458874cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTU1MjUsIm5iZiI6MTczMjA5NTIyNSwicGF0aCI6Ii85NjI0NTE4My8zODgwMzI4OTUtNWZmYzEzODktMmY2NC00NmQzLWI3MjAtMjA1NTQ1ODg3NGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA5MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNWRjNGNhZTZkZGE5YzJhOTExNmE1MzRlZmQ5MGM5YTA3MDQzYjU1YzEyMGQ5YWNjYmZlZDA5NDBhMTRmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iwXkHLp6W6QX6fr5mmNwK-YOjaXWIaj7nOyrspSVAc4">

**Comment by luziusmeisser** [comment]
thanks!
