### ISSUE TITLE
Profile picture not loading from ENS

### ISSUE THREAD

**Issue by johanneskern** [Frankencoin-ZCHF/frankencoin-dapp#143]
![image](https://github.com/user-attachments/assets/174b37e4-f543-42bf-bb53-86e2408a6cef)

**Comment by samclassix** [comment]
# this is an imported module from wagmi

> if picture is not loading, the issue is on there side

<img width="373" alt="Screenshot 2024-12-02 at 2 11 11 PM" src="https://github.com/user-attachments/assets/971d33a2-d43b-4073-94c1-a1fb26dda2af">
