### ISSUE TITLE
Max on adjust page wrong

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#144]
<img width="460" alt="image" src="https://github.com/user-attachments/assets/b2b48044-3fc6-4965-9a29-aa02d38e1d99">

Looked into the code. Problem is that the frontend is using "availableForClones" even though this is not about a clone.

I would advise to drop the "availableForMinting" and the "availableForClones" variables in the position. In the 2024 version, the available amount for one position depends on its siblings in the same position family. Instead, I would simply get the amount dynamically from the smart contract, using a call to "availableForMinting()".

**Comment by samclassix** [comment]
V2 done.
