### ISSUE TITLE
The app does not recognize if the wallet is connected to the wrong blockchain. 

### ISSUE THREAD

**Issue by TaprootFreak** [Frankencoin-ZCHF/frankencoin-dapp#25]
I have tried. to exchange approx. 100 ZCHF for FPS. However, my Metamask was connected to Arbitrum and not to Ethereum.

Instead of throwing an error message, Frankencoin simply passed the command to Metamask and Metamask executed it. On the wrong blockchain 😁

<img width="578" alt="Bildschirmfoto 2024-02-14 um 20 59 52" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/142087526/ac903456-35cd-49ff-880c-59a78d0cfdfc">
  

<img width="405" alt="Bildschirmfoto 2024-02-14 um 21 00 02" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/142087526/bbe4e51e-ace6-4354-bd05-92624b9485a1">
  

<img width="350" alt="Bildschirmfoto 2024-02-14 um 21 00 12" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/142087526/ce25e16b-eaeb-4c7c-92b2-6d2b0fa1f310">
  
<img width="559" alt="Bildschirmfoto 2024-02-14 um 21 07 10" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/142087526/d3ea72b3-1d91-49dc-b0f6-8d48dd34a386">
  

It should be easy to detect an incorrect network and force a network change directly.

**Comment by samclassix** [comment]
you are right. Detection of the correct chain is quite important. ;)

This should fix it. 
https://github.com/Frankencoin-ZCHF/frankencoin-dapp/pull/35
