### ISSUE TITLE
WalletConnect not properly configured

### ISSUE THREAD

**Issue by gianbrun** [Frankencoin-ZCHF/frankencoin-dapp#27]
WalletConnect is somehow not properly configured and gets display as Web3Modal in the WalletConnect overview of a wallet.
![IMG_D22CA4A71F80-1](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/22100466/03d0c5c5-fc16-4156-9f0c-14c3ff055c5d)

**Comment by samclassix** [comment]
should be solved with current dev branch, check out devapp.frankencoin.com for the latest alpha/beta version of the frankencoin dapp
