### ISSUE TITLE
Add ZCHF on Base

### ISSUE THREAD

**Issue by TaprootFreak** [Frankencoin-ZCHF/frankencoin-dapp#29]
Token: https://basescan.org/token/0x20D1c515e38aE9c345836853E2af98455F919637
Uniswap: USDC to ZCHF: https://app.uniswap.org/swap?inputCurrency=0xd9aaec86b65d86f6a7b5b1b0c42ffa531710b6ca&outputCurrency=0x20d1c515e38ae9c345836853e2af98455f919637&chain=base

**Comment by samclassix** [comment]
Instructed to close.
