### ISSUE TITLE
Sort Positions

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#41]
It should be possible to sort the positions table by "collateral type", "liquidation price", and "available amount".

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/49c2abed-7fb8-4a5b-8472-a0110a4a60c8)

**Comment by AndreasFC94** [comment]
And clearly show new positions that can still be vetoed.

**Comment by samclassix** [comment]
### This will be solved in the UI 2.0

https://github.com/Frankencoin-ZCHF/frankencoin-dapp/blob/samclassix-develop-positions-view-ui/.dev/samclassix-202406/samclassix-202406-PositionTabs.png

### UI Development under progress
branch: samclassix-develop-positions-view-ui
[samclassix-develop-positions-view-ui](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/tree/samclassix-develop-positions-view-ui)
