### ISSUE TITLE
Create alerts for new positions

### ISSUE THREAD

**Issue by AndreasFC94** [Frankencoin-ZCHF/frankencoin-dapp#45]
Email alerts for new proposed positions. An alert needs to be sent out as soon as any new position is proposed. This needs an easy sign-up process.

**Comment by samclassix** [comment]
From where does the email come from? its not linked to any addresses or accounts.

If we want to have backend tasks and schedules we should consider to deploy a detached backend service for those tasks (e.g. NestJS framework, Schedule Module, Email Service, ...).

**Comment by samclassix** [comment]
@AndreasFC94 
Priority: July?

**Comment by AndreasFC94** [comment]
Yes - July sounds good as there are more urgent issues that need to be taken care of

**Comment by samclassix** [comment]
Most likely we will use the telegram api. Will check it out next week, then we can talk about this again.

**Comment by samclassix** [comment]
Done. Api v0.0.9
