### ISSUE TITLE
Implement a Register of Companies Accepting ZCHF on the Website

### ISSUE THREAD

**Issue by AndreasFC94** [Frankencoin-ZCHF/frankencoin-dapp#46]
We need to implement a new feature on our website that lists all the companies accepting ZCHF. This will help promote the use of Frankencoin and provide our users with a clear directory of where they can spend their ZCHF.

**Comment by luziusmeisser** [comment]
This issue belongs to the landing page, namely https://github.com/Frankencoin-ZCHF/www . Please file it there and not in the app.
