### ISSUE TITLE
Move to latest versions

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#48]
We should move the project to the latest versions of the used dependencies, including wagmi. This could also be the basis to fix the performance issues.

**Comment by samclassix** [comment]
### Solved. 

```
before:
"viem": "^1.19.15",
"wagmi": "^1.4.12"

after:
"viem": "^2.13.3",
"wagmi": "^2.9.8"
"@types/react": "^18.3.3",
"@types/react-dom": "^18.3.0",
```

branch: samclassix-develop-positions-view-ui
commit: https://github.com/Frankencoin-ZCHF/frankencoin-dapp/commit/8dd831b5e48912d7e9c670e7fb25ea6a0f14bba3
[8dd831b5e48912d7e9c670e7fb25ea6a0f14bba3](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/commit/8dd831b5e48912d7e9c670e7fb25ea6a0f14bba3)
#### Discussion moved to #49 (Frontend 2.0)
