### ISSUE TITLE
Frontend 2.0

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#49]
We should think about how we should move the frontend forward. Most importantly, it would be good to bring today's position page to a higher level of abstraction. It could become a "borrow" page that allows the user to comfortably borrow against a collateral detected in the users wallet.

An open question is whether managing existing positions would still be on this page or not. Could potentially be moved to a separate tab.

**Comment by samclassix** [comment]
### UI/UX
* Loading Screen for loading initial application state. (BlockUpdater Component Guard)

**Comment by samclassix** [comment]
### Positions UI Proposal
https://github.com/Frankencoin-ZCHF/frankencoin-dapp/blob/samclassix-develop-positions-view-ui/.dev/samclassix-202406/samclassix-202406-PositionTabs.png

UI Development under progress
branch: samclassix-develop-positions-view-ui
[samclassix-develop-positions-view-ui](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/tree/samclassix-develop-positions-view-ui)

**Comment by samclassix** [comment]
### Wagmi. Viem, Types, Tailwind, React, ... updated

branch: samclassix-develop-positions-view-ui
commit: 8dd831b5e48912d7e9c670e7fb25ea6a0f14bba3
[8dd831b5e48912d7e9c670e7fb25ea6a0f14bba3](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/commit/8dd831b5e48912d7e9c670e7fb25ea6a0f14bba3)

### Testing for writeContract not tested. Will be tested in the future with sepolia chain and new UI development.

**Comment by samclassix** [comment]
# State update between components -> move to redux store?

### What happened?
- e.g. Approving a transfer tx
- after tx confirmation (Toster Await)
- btn does not change/update state 

![Screenshot 2024-06-08 at 10 57 38 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/851b7bbc-ffac-405c-bf6f-661b0744bec2)

**Comment by samclassix** [comment]
# Approve max value? 
Click on btn will create a tx with max spendable about. Is this wanted like this?

![Screenshot 2024-06-08 at 12 40 42 PM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/aa504f39-ebc1-4a9f-8be4-e0d969c816c2)

**Comment by luziusmeisser** [comment]
> ### Positions UI Proposal
> https://github.com/Frankencoin-ZCHF/frankencoin-dapp/blob/samclassix-develop-positions-view-ui/.dev/samclassix-202406/samclassix-202406-PositionTabs.png
> 
> UI Development under progress branch: samclassix-develop-positions-view-ui [samclassix-develop-positions-view-ui](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/tree/samclassix-develop-positions-view-ui)

We should discuss this on Tuesday at the jour fixe in person. Having the UI react differently just based on a filter seem not very intuitive. Filters should not change how items behave. We need completely distinct views with different values in the table tailored towards the three use cases: own positions, borrow, observatory. Also, clicking a position should yield a consistent result, but we can always change the button label depending on the view.

**Comment by luziusmeisser** [comment]
> # Approve max value?
> Click on btn will create a tx with max spendable about. Is this wanted like this?
> 
> ![Screenshot 2024-06-08 at 12 40 42 PM](https://private-user-images.githubusercontent.com/96245183/337868724-aa504f39-ebc1-4a9f-8be4-e0d969c816c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MjE3ODcsIm5iZiI6MTcxNzkyMTQ4NywicGF0aCI6Ii85NjI0NTE4My8zMzc4Njg3MjQtYWE1MDRmMzktZWJjMS00YTlmLThiZTQtZTBkOTY5YzgxNmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDA4MjQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYmM5OTA0NGYwOGQwODI0NDA3MGFkYmJkMjc4YTFjMGU4ODU0YjU5MzcwZTM1MmM5MDY2YWI3NDNmMmNhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ywgAMki9348WWevM3ZvlM3uEvbhj92MxQKILodoFafA)

Yes, this is intended to save gas on subsequent calls. I think for immutable and audited contracts, this is acceptable behavior.
