### ISSUE TITLE
Toasters don't disappear in "Propose Position" page

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#61]
The two toasters did not disappear even long after the transactions completed.

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/e2cc61b8-1a22-43d1-8c1c-7874cc8bd4af)

**Comment by samclassix** [comment]
We need sepolia to test the App.

**Comment by samclassix** [comment]
Worked fine on updated pkg version. 
All toasters/writeContract functions needed a quick adjustment due to major version update, anyways.
