### ISSUE TITLE
Support different Equity Modules. Invest, Wrapping, UnwrapAndSell, UnlockAndRedeem, bridging, ...

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#63]
- [x] Swap between ZCHF and FPS
- [x] Wrap and Unwrap
- [x] Unwrap and Redeem (Sell)
- [x] remake and merge to a single module with token dropdown menu

**Comment by luziusmeisser** [comment]
The function that is to be called when redeeming WFPS is different from the function for redeeming FPS. For WFPS, it is:

wfps.unwrapAndSell(uint256 amount)

See also here:
https://etherscan.io/address/0x5052d3cc819f53116641e89b96ff4cd1ee80b182#writeContract

The maximum amount is the WFPS balance of the user. And to check the holding period, you have to get the FPS holding period of the WFPS contract, i.e.:

fps.holdingDuration(wfps)

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/ec266e73-767e-4310-8043-1a65b06b1b67)

At the time of writing, this is 5982719 seconds, or 69 days, so the button would be disabled!

**Comment by samclassix** [comment]
# Select modules/methods support
<img width="1792" alt="Screenshot 2024-09-17 at 9 36 13 AM" src="https://github.com/user-attachments/assets/e4f8d6f2-6e10-4d06-b325-6798955f1664">

# Module: Swap between ZCHF and FPS 
> Method(s): FPS.Invest() or FPS.Redeem()
<img width="615" alt="Screenshot 2024-09-17 at 9 38 33 AM" src="https://github.com/user-attachments/assets/24c15b61-19ea-49f1-9e54-84c12ffd7eea">

# Module: Wrap FPS and Unwrap WFPS
> Methods: WFPS.depositFor() or WFPS.withdrawTo()
<img width="614" alt="Screenshot 2024-09-17 at 9 38 43 AM" src="https://github.com/user-attachments/assets/8fd82795-496a-4bae-9dc3-cd3f602e66df">

# Redeem WFPS for ZCHF
> Method: WFPS.unwrapAndSell()
<img width="616" alt="Screenshot 2024-09-17 at 9 38 52 AM" src="https://github.com/user-attachments/assets/0165d73f-83b4-41ad-b8fa-cb17256d185d">

# Unlock FPS for ZCHF
> Method: Unlock.unlockAndRedeem()
<img width="617" alt="Screenshot 2024-09-17 at 9 39 02 AM" src="https://github.com/user-attachments/assets/57ecde50-ada3-4f38-9f6b-2f8800b42223">

**Comment by samclassix** [comment]
# change in words
<img width="631" alt="Screenshot 2024-09-17 at 10 06 20 AM" src="https://github.com/user-attachments/assets/501bdea8-35b9-4b38-886f-6342d27624e1">

**Comment by luziusmeisser** [comment]
I think drop-down menues are not supposed to be used to select a page. They should be reserved for selecting inputs. As an alternative for the drop down at the top, we could consider tabs. But also tabs are somewhat clumsy, especially since we aready have tab-like sections at the top of the page.

Why don't we imitate uniswap and go for something like this:

![image](https://github.com/user-attachments/assets/eb40f057-b89b-4405-84e8-aea1b1312617)

Here, it would be possible to select ZCHF, FPS, and WFPS both in the top and the bottom field. Also, the arrow should indicate in which direction the swap is taking place. The two-sided arrow did not make much sense. Like on uniswap, clicking the arrow would swap the two selections, but it would not change the arrow.

Default selection should be ZCHF -> FPS
Other valid selections are: FPS -> ZCHF, WFPS -> ZCHF, FPS -> WFPS, WFPS -> FPS

For the four other selections, the button should be disabled without label. The label of the button should be "Mint", "Redeem", "Wrap" and "Unwrap" in the other cases, depending on the selection.

**Comment by samclassix** [comment]
considered done.
PR https://github.com/Frankencoin-ZCHF/frankencoin-dapp/pull/117
