### ISSUE TITLE
Support FPS Bridging and Wrapping in App

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#64]
We should rework this area in the pool page (https://app.frankencoin.com/pool):

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/5e9a2990-ebf3-46b6-8fb5-71bfed175ddc)

It should show the users balance of FPS, WFPS and Polygon WFPS. It should contain etherscan links to all three token contracts as well as a link to defillama swap where polygon WFPS can be swapped to polygon ZCHF. Furthermore, we should think about how we could support wrapping, unwrapping, bridging and unbridging.

**Comment by samclassix** [comment]
discussion moved to #63
