### ISSUE TITLE
Own position not clonable. Intended?

### ISSUE THREAD

**Issue by samclassix** [Frankencoin-ZCHF/frankencoin-dapp#65]
# If you own positions, you can't clone.

- Why should we have this behavior?
- Why do we restrict buttons for navigation?
- Why do we force the user to manually navigate (forces a reload of the whole app incl. redux store)? 

![Screenshot 2024-06-10 at 9 57 49 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/adc12d0b-3e77-450f-a0d1-efb8e51e8da5)
![Screenshot 2024-06-10 at 9 57 58 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/80ddd0d7-ee6d-4a91-8d93-ea67962f4373)

# Do we want to adjust this or is this an intended behavior?

**Comment by luziusmeisser** [comment]
Cloning your own position is kind of pointless. This is by design.
