### ISSUE TITLE
Layouting Issue with Icons

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#69]
<img width="191" alt="image" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/d93d489c-27cf-4038-b905-b90d217e230e">

Spotted in the adjust position window: there is no space between the icon and the text box. I think that should be.

**Comment by samclassix** [comment]
# Fixed. Can be merged with the next version upgrade.

### development branch: samclassix-develop-positions-view-ui
### commit: [2bf08c0](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/pull/68/commits/2bf08c0e422cddcfb36f2565e0bbe75675744c77)
