### ISSUE TITLE
Data on Adjust page sometimes odes not load

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#70]
Steps to reproduce:

1. Go to positions page and click the adjust button:
![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/c5fc6c57-e568-4372-9ad4-8ba5e1cb6fa5)

2. You sometimes get this:
![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/3920e99e-498b-401b-92b9-8b234437c60c)

The expected behavior would be seeing this (i.e. having filled in text fields):
![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/62112d11-a620-4f06-9f4c-e388a068ea6d)

As a small bonus bug: on the above screen, clicking the marked amount "0.00 CHF" has no effect:
![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/173d7604-ac1b-4d26-aac5-ad9cc4d3cbc8)

I would expect the amount to be filled into the text field like this, even if it is 0. Note that it works for values other than 0.

![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/207fa4f9-54d4-4939-95fc-4a9534443fb5)

**Comment by samclassix** [comment]
fixed in the new version.
Need to restrict clones. Because they follow their static minting limit, independent of the collateral amount.
