### ISSUE TITLE
Correct rounding

### ISSUE THREAD

**Issue by TaprootFreak** [Frankencoin-ZCHF/frankencoin-dapp#71]
The ZCHF display is not rounded correctly. 

app.frankencoin.com
<img width="243" alt="Bildschirmfoto 2024-06-12 um 13 55 05" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/142087526/984443b0-77b4-418f-89cd-18f506c731d7">

frankencoin.com
<img width="318" alt="Bildschirmfoto 2024-06-12 um 13 55 01" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/142087526/b0861821-30df-4db9-afd8-82ecce4fd6cb">

The exact amount is 9587126.505745564

**Comment by samclassix** [comment]
solved with the new api. => mintburnmapping
