### ISSUE TITLE
samclassix-develop-layout-ui

### ISSUE THREAD

**Issue by samclassix** [Frankencoin-ZCHF/frankencoin-dapp#73]
# Updates in the UI / Navbar / Position Pages
## Screenshots

![Screenshot 2024-06-24 at 8 39 52 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/372660e9-7023-4adf-a1a9-4cb64215a762)

![Screenshot 2024-06-24 at 8 39 57 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/ed2959ef-1166-4d38-81aa-ebab4d061614)

![Screenshot 2024-06-24 at 8 40 04 AM](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/96245183/a7f6b94d-c343-41c9-8201-4e843aec5dcf)

**Comment by luziusmeisser** [comment]
I see that the old landing screen was disabled.

Before disabling it, we should make sure that all information from the old landing page is also available on the new one.

Most importantly, the new www page should contain links to all token contracts on all chains, links to the bridges to those chains, and links to defi llama swap so one can buy and sell all flavors of the ZCHF and FPS.

This is a task for @TaprootFreak

**Comment by luziusmeisser** [comment]
For the frontend, a click onto the icon should send the user back to the landing page (frankencoin.com). The page that loads in the alpha version when clicking on the top left icon is not necessary and can be dropped.

**Comment by luziusmeisser** [comment]
We should also drop the auctions tab.

"Your auctions" should be included under "My positions".

"All auctions" should be moved to "Supervision".

**Comment by samclassix** [comment]
# Supervision

> I see that the old landing screen was disabled.
> 
> Before disabling it, we should make sure that all information from the old landing page is also available on the new one.
> 
> Most importantly, the new www page should contain links to all token contracts on all chains, links to the bridges to those chains, and links to defi llama swap so one can buy and sell all flavors of the ZCHF and FPS.
> 
> This is a task for @TaprootFreak

Nice :) 

@TaprootFreak 
if you need details about the collateral within the frankencoin system and the mint token, check out the new api service. 
Currently Collateral Live on: https://api.frankencoin.3dotshub.com/prices/collateral
Currently Mint Live on: https://api.frankencoin.3dotshub.com/prices/mint

=> Swagger: https://api.frankencoin.3dotshub.com

**Comment by samclassix** [comment]
> For the frontend, a click onto the icon should send the user back to the landing page (frankencoin.com). The page that loads in the alpha version when clicking on the top left icon is not necessary and can be dropped.

@luziusmeisser 
Should the landing page:
a) open in the same tab
b) open in a new tab

**Comment by samclassix** [comment]
> In My positions, the horizontal slider with the collaterals is not needed and should be removed.
> 
> ![image](https://private-user-images.githubusercontent.com/3128389/342234142-b558ee04-8ad1-434c-b907-5fab41bad8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTQyNTIsIm5iZiI6MTcxOTIxMzk1MiwicGF0aCI6Ii8zMTI4Mzg5LzM0MjIzNDE0Mi1iNTU4ZWUwNC04YWQxLTQzNGMtYjkwNy01ZmFiNDFiYWQ4ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDcyNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFkMmEwZWRlMDg5NWM4MjA0NTBjNDgzN2FkYWYzNDEzZWQ1NTcxZWFhYjE1ZjJiODcwM2Q5NjMxYzJjZmMwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0umDJeLWfjyoxzvdRjLkgyCgz1bP1rGlg2EcBM2evMU)

Should we display different data in the horizontal slider component? 
e.g. <Token, Amount of owned positions, Amount of owned challenges, Worst owned collateral state> ?

**Comment by luziusmeisser** [comment]
> Should we display different data in the horizontal slider component? e.g. <Token, Amount of owned positions, Amount of owned challenges, Worst owned collateral state> ?

No, I think we can simply drop it.

**Comment by luziusmeisser** [comment]
I think we should go back to the old table layout. It was cleaner and more compact. Now it is:

<img width="965" alt="image" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/35f6a945-27f9-4df2-aa48-09cb93a9cf7b">

Before it was:
![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/f405cc83-701b-4af3-a790-9eaffab960cc)

Here is how I would do it:
<img width="946" alt="image" src="https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/b8e5dd99-a123-4553-8f26-7f967a3c2f57">

Very simple and reduced to the essential information. "Clone & Mint" should be renamed to "Borrow".

**Comment by luziusmeisser** [comment]
The [/] should be the outside link indicator. :)
When clicking the position, we should go to the position page.
When clicking the borrow button, we should directly go to the borrow page.

**Comment by luziusmeisser** [comment]
Note that in the current alpha, navigation is broken. When starting at "borrow" and selecting a position, there is a link "back to positions" that does not take you back but to the "my positions" page. We should remove that link.
![image](https://github.com/Frankencoin-ZCHF/frankencoin-dapp/assets/3128389/f6d36d0a-553d-4704-ac5a-3f1f00d68687)

**Comment by luziusmeisser** [comment]
Also, let's drop the top slider everywhere. To me, it is too distracting. We can discuss, but it seems like it does not add much value and at the same time draws too much attention.
