### ISSUE TITLE
Frontend does not update automatically after signing an approval transaction

### ISSUE THREAD

**Issue by KostasZav** [Frankencoin-ZCHF/frankencoin-dapp#74]
When swapping XCHF to ZCHF on the Frankencoin website, the frontend does not update automatically after a user signs an approval transaction. This results in a somewhat poor user experience.

**Steps to Reproduce:**
1. Navigate to the swap page at https://app.frankencoin.com/swap.
2. Select XCHF as the input ("Send") and ZCHF as the output ("Receive").
3. Initiate the swap process which requires signing an approval transaction.
4. Sign the approval transaction.

**Actual Behavior:**
The frontend does not update automatically after signing the approval transaction. The user has to manually refresh the page to see the updated status, leading to potential signing of multiple approval transactions.

**Expected Behavior:**
The frontend should automatically update after the approval transaction is signed, preventing the user from signing multiple approval transactions unnecessarily

**Comment by samclassix** [comment]
updated allowance, is updated in the new version. However, Swap Bridge will loose support in the future.
