### ISSUE TITLE
Borrow tab revision

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#82]
Changes in words, Check List:

- [x] Removing the horizontal slider
- [x] Remove subtitles in header, shorten labels
- [x] Stick to the basic colors (white for the header font, light blue for the content), only style effect is bold vs. normal font
- [x] Add the "mint" button that leads to for example 
- [x] Clicking the position should not have an effect any more (as it can be confusing on mobile)
- [x] Clicking on the symbol of the collateral should open the collateral's etherscan page
- [ ] Clicking on the titles should sort the table by that title (alphabetically by collateral name, in decreasing order by interest, and in decreasing order by LTV)
- [x] ??? https://app.test.frankencoin.com/borrow/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3

----
Latest test version of the borrow tab looks as follows:

![image](https://github.com/user-attachments/assets/c048a587-bfbe-47fa-b9cb-6854f34b0330)

I would simplify the screen as follows:

<img width="968" alt="image" src="https://github.com/user-attachments/assets/03d5edf2-1338-4ce2-850d-6d7ecfeabe8f">

(Please excuse the inconsistent layout, headers should of course all have the same style, same for the text, where I think a semi-bold light blue font would probably be a good choice and a normal font for the name of the collateral below the symbol.)

More details in the comments below.

**Comment by luziusmeisser** [comment]
Responsive layout: as the table gets more narrow, it is ok to drop the maturity and available columns.

<img width="685" alt="image" src="https://github.com/user-attachments/assets/e3e09f6d-f5d3-474f-bd3c-f16bbf1c48cd">

For very narrow screens, we might have to resort to a card layout, maybe like this:

<img width="318" alt="image" src="https://github.com/user-attachments/assets/cf3a76e4-339e-4f34-8bf2-75c79842ee3d">

(Here I am not sure. Feel free to suggest alternatives, we might need to do multiple iterations or wait for the input from the UX guys.)

**Comment by luziusmeisser** [comment]
Changes in words:
- Removing the horizontal slider
- Remove subtitles in header, shorten labels
- Stick to the basic colors (white for the header font, light blue for the content), only style effect is bold vs. normal font
- Add the "mint" button that leads to for example https://app.test.frankencoin.com/borrow/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
- Clicking the position should not have an effect any more (as it can be confusing on mobile)
- Clicking on the symbol of the collateral should open the collateral's etherscan page
- Clicking on the titles should sort the table by that title (alphabetically by collateral name, in decreasing order by interest, and in decreasing order by LTV)

**Comment by luziusmeisser** [comment]
Related: issue #83

**Comment by luziusmeisser** [comment]
Consistently with #83 , I would rename the path from
https://app.test.frankencoin.com/borrow
to 
https://app.test.frankencoin.com/mint

**Comment by samclassix** [comment]
Changes in words, Check List:

- [x] Removing the horizontal slider
- [ ] Remove subtitles in header, shorten labels
- [ ] Stick to the basic colors (white for the header font, light blue for the content), only style effect is bold vs. normal font
- [ ] Add the "mint" button that leads to for example 
- [ ] https://app.test.frankencoin.com/borrow/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
- [x] Clicking the position should not have an effect any more (as it can be confusing on mobile)
- [ ] Clicking on the symbol of the collateral should open the collateral's etherscan page
- [ ] Clicking on the titles should sort the table by that title (alphabetically by collateral name, in decreasing order by interest, and in decreasing order by LTV)

**Comment by samclassix** [comment]
moved to #87
