### ISSUE TITLE
Mint page

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#83]
- [x] Remove the link "back to position". Instead, there is a line "parent position" in the notes section that links to the position page, e.g. https://app.frankencoin.com/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
> e.g. https://app.frankencoin.com/monitoring/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
- [x] Amount field should be pre-filled with the minimum, i.e. minimum collateral * liquidation price
- [ ] I would tend to have only one place to show the error, namely below the button. Here, the user has insufficient BTC in his wallet.
- [x] We can remove the explanation below the collateral field "Valued at...." in the previous screenshot. The minimum will be communicated in the error text when below, the liquidation price is shown in notes.
- [ ] In the Outcome section, the percentages for sent to the wallet and for the retained reserve should be given. The fee percentage is the same.
- [ ] We adjust the notes section to show how the effective interest and the loan-to-value shown on the borrow page are calculated.

---

This is about how to adjust the mint page that currently looks like this:

![image](https://github.com/user-attachments/assets/d7de3f37-1cbd-425b-887d-3279fd5447d9)

The url currently has this format:
https://app.test.frankencoin.com/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3/borrow

I personally would prefer to have the path as follows:
https://app.test.frankencoin.com/mint/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3

**Comment by luziusmeisser** [comment]
Here is how I would revise this dialog:

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/ff70ed90-1ab2-424a-98d4-fc51ac8ad9be">

1. Remove the link "back to position". Instead, there is a line "parent position" in the notes section that links to the position page, e.g. https://app.frankencoin.com/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
2. Amount field should be pre-filled with the minimum, i.e. minimum collateral * liquidation price
3. I would tend to have only one place to show the error, namely below the button. Here, the user has insufficient BTC in his wallet.
4. We can remove the explanation below the collateral field "Valued at...." in the previous screenshot. The minimum will be communicated in the error text when below, the liquidation price is shown in notes.
5. In the Outcome section, the percentages for sent to the wallet and for the retained reserve should be given. The fee percentage is the same.
6. We adjust the notes section to show how the effective interest and the loan-to-value shown on the borrow page are calculated.

**Comment by samclassix** [comment]
# Outcome % are dependent on expiration
<img width="569" alt="Screenshot 2024-08-07 at 11 24 11 AM" src="https://github.com/user-attachments/assets/5333a9aa-1448-4b2c-9b10-8d274ef83413">

# incl. Bug #100 
# done.
