### ISSUE TITLE
Supervision (Monitoring) tab revision

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#84]
- [x] Collateralization. This is (market price)/(liquidation price) and should always be above 100%.
- [x] Expiration: this is a countdown to the expiration of the position. I would only show the most significant unit. So if it is 13 days, 6 hours and 3 minutes until expiration, I would only show "13 days". And once it is less than one day, I would show "6 hours", etc.
- [x] Challenges: this is usually 0% and tells the user what fraction of the position has already been challenged. This can be above 100%. For example, if the position has 1 BTC collateral and there are two challenges, one challenging 0.3 BTC and one challenging 0.8 BTC, this number is 110%.
- [x] In the end, there is a button that leads to the challenge page, which can currently be found under path https://app.test.frankencoin.com/monitoring/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3/challenge

It should be possible to order the columns by their title:
- [ ] Collateral: decreasing order (biggest first by market value)
- [ ] Collateralization: increasing order (lowest first)
- [ ] Expiration: increasing order (soonest first)
- [ ] Challenges: decreasing order (highest first)
- [ ] By default, the table should be sorted by collateralization.

---

This is what the current version looks like:

![image](https://github.com/user-attachments/assets/f819129c-465d-42d1-a1c8-8289880add53)

First, I think the tab and the path should be renamed to monitoring, i.e.
https://app.test.frankencoin.com/monitoring
instead of
https://app.test.frankencoin.com/supervision

Then, I would suggest to focus on the essentials as follows:

<img width="673" alt="image" src="https://github.com/user-attachments/assets/084cded8-00df-41a4-aa43-2148c58af44e">

In contrast to the borrow page, it is relevant to know how big the position is, so I would provide a concrete amount in the "collateral" tab. Next important metrics are:
- Collateralization. This is (market price)/(liquidation price) and should always be above 100%.
- Expiration: this is a countdown to the expiration of the position. I would only show the most significant unit. So if it is 13 days, 6 hours and 3 minutes until expiration, I would only show "13 days". And once it is less than one day, I would show "6 hours", etc.
- Challenges: this is usually 0% and tells the user what fraction of the position has already been challenged. This can be above 100%. For example, if the position has 1 BTC collateral and there are two challenges, one challenging 0.3 BTC and one challenging 0.8 BTC, this number is 110%.
- In the end, there is a button that leads to the challenge page, which can currently be found under path https://app.test.frankencoin.com/supervision/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3/challenge . However, we might want to revise that path to https://app.test.frankencoin.com/challenge/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3 or https://app.test.frankencoin.com/monitoring/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3, whichever you prefer.

It should be possible to order the columns by their title:
- Collateral: decreasing order (biggest first by market value)
- Collateralization: increasing order (lowest first)
- Expiration: increasing order (soonest first)
- Challenges: decreasing order (highest first)

By default, the table should be sorted by collateralization.

**Comment by luziusmeisser** [comment]
When showing the table of narrow screens, the column "challenges" can be dropped. And when it gets even more narrow, we can choose a layour similar to what was described here: https://github.com/Frankencoin-ZCHF/frankencoin-dapp/issues/82

**Comment by luziusmeisser** [comment]
Also, the horizontal slider should be dropped.

Filtering: all open positions should be shown, including those that have 0 minted ZCHF. What matters is that they have collateral in them.

**Comment by luziusmeisser** [comment]
Note: this revision does not offer any way to veto a newly proposed position. I think that feature should be moved to the governance page. It is also not very important for now.

**Comment by luziusmeisser** [comment]
Just noticed: the "Propose New Position Type" should be dropped here. It is only relevant in the Borrow context.

![image](https://github.com/user-attachments/assets/63d801a6-ff4c-421f-bb5a-24e77fdd39ff)

**Comment by samclassix** [comment]
> Also, the horizontal slider should be dropped.
> 
> Filtering: all open positions should be shown, including those that have 0 minted ZCHF. What matters is that they have collateral in them.

- [x] hor. slider dropped
- [x] **???** all open positions incl. those that have 0 minted zchf, have always been shown. Need feedback otherwise.

see example:

![Screenshot 2024-07-22 at 10 48 38 AM](https://github.com/user-attachments/assets/8d4d1a4e-d876-4264-9b7f-086edec5a7e2)

**Comment by samclassix** [comment]
<img width="1418" alt="Screenshot 2024-07-23 at 7 51 21 AM" src="https://github.com/user-attachments/assets/7303ba09-ed7a-4a87-ad64-ffa8a242ce24">

## @luziusmeisser What do you prefer?

- [ ] text-red-700
- [ ] text-red-500
- [ ] text-red-300

**Comment by luziusmeisser** [comment]
I think text-red-500 is good for now. As soon as we have the new style guide, we will have to adjust this to an official color from the palette.

**Comment by samclassix** [comment]
moved to #87
