### ISSUE TITLE
My Positions Tab Review

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#85]
- [x] Collateral icon, collateral amount, its market value in CHF
- [x] Liquidation price in ZCHF and market price in CHF. Liquidation price should be printed bright red and bold if it is less than 10% above the market price
- [x] Minted amount and limit.
- [x] State and time left of the current state
- [x] The "Adjust" button

The rule for the state is as follows:
- [x] If there are one or more pending challenges, the state is "Challenged" in bold red and the countdown below shows how much time is left until the next challenge enters phase 2. If there already is a challenge in phase 2, the countdown can be at 00:00:00. Also, the "Challenged" text should link to the position overview, where one can see the challenges, that is for example https://app.frankencoin.com/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
- [x] If the position is new (i.e. current time is before start), the label should be "New" and the countdown show the time until start is reached
- [x] If the position is closed (i.e. isClosed() returns true), it should simply say "Closed" without any timer
- [x] If the position is in cooldown (i.e. the variable cooldown is in the future), it says "Cooldown" with the timer showing the time until cooldown is reached
- [x] If expiration is less than a week away, it should say in bold red "Expiring soon" with the expiration timer below
- [x] If none of the above applies, then the state is "Open" with the timer indicating the time until its expiration. 

Adjust Page
- [x] Need to restrict minting, with limit. Minting limit is independent of the collateral amount. Calculation and Logic somewhere wrong.
---

Currently looks like this:

![image](https://github.com/user-attachments/assets/7671c11f-6f13-475f-8a7c-7279c68be9fc)

I would suggest to revise the content as follows (disregard colors and styles):

<img width="814" alt="image" src="https://github.com/user-attachments/assets/6be80f08-e87f-4c74-a59f-6e98937999ea">

The columns would then be as follows:
- Collateral icon, collateral amount, its market value in CHF
- Liquidation price in ZCHF and market price in CHF. Liquidation price should be printed bright red and bold if it is less than 10% above the market price
- Minted amount and limit.
- State and time left of the current state
- The "Adjust" button

The rule for the state is as follows:
- If there are one or more pending challenges, the state is "Challenged" in bold red and the countdown below shows how much time is left until the next challenge enters phase 2. If there already is a challenge in phase 2, the countdown can be at 00:00:00. Also, the "Challenged" text should link to the position overview, where one can see the challenges, that is for example https://app.frankencoin.com/position/0x98725eE62833096C1c9bE26001F3cDA9a6241EF3
- If the position is new (i.e. current time is before start), the label should be "New" and the countdown show the time until start is reached
- If the position is closed (i.e. isClosed() returns true), it should simply say "Closed" without any timer
- If the position is in cooldown (i.e. the variable cooldown is in the future), it says "Cooldown" with the timer showing the time until cooldown is reached
- If expiration is less than a week away, it should say in bold red "Expiring soon" with the expiration timer below
- If none of the above applies, then the state is "Open" with the timer indicating the time until its expiration.

**Comment by luziusmeisser** [comment]
Also, the "Propose new position type" button should be removed.

**Comment by samclassix** [comment]
Actually, its still ZCHF instead of CHF.
Because, collateral prices are in e.g. WBTC/USD from coingecko.
And ZCHF is also ZCHF/USD from coingecko. So the "markt price" is e.g. ZCHF/WBTC.

**Comment by luziusmeisser** [comment]
You are right, let's stick with ZCHF.

**Comment by samclassix** [comment]
<img width="628" alt="Screenshot 2024-07-23 at 7 56 53 AM" src="https://github.com/user-attachments/assets/af38c833-0623-4454-adfa-ff512c8ca9b1">

# text-red-700 & font-bold

**Comment by samclassix** [comment]
# Requested (new position)
<img width="1083" alt="Screenshot 2024-07-23 at 8 34 06 AM" src="https://github.com/user-attachments/assets/d44de854-ae96-48a5-a5f7-cf6f153f4f72">

```
state: "Requested"
time format: "{_d}d {_h}h {_m}m"
```

**Comment by samclassix** [comment]
# Ready

state: "Ready"
stateTime: days to expiration

<img width="1083" alt="Screenshot 2024-07-23 at 8 36 52 AM" src="https://github.com/user-attachments/assets/c0b582b3-8bac-4ee1-9514-3d61e61e94f4">

# Expiring Soon

state: "Expiring Soon"
stateTime: days to expiration

<img width="1092" alt="Screenshot 2024-07-23 at 8 39 24 AM" src="https://github.com/user-attachments/assets/72b0840c-63d5-41a9-9650-c307ed3f5218">

**Comment by samclassix** [comment]
![Uploading Screenshot 2024-07-23 at 8.40.30 AM.png…]()

**Comment by samclassix** [comment]
# Closed
<img width="1087" alt="Screenshot 2024-07-23 at 8 40 58 AM" src="https://github.com/user-attachments/assets/a8b962f2-20f9-46d6-885d-065bcfee5dbc">

**Comment by samclassix** [comment]
# Cooldown

```
state: "Requested" --> changed to "New Request"
time format: "{_d}d {_h}h {_m}m"
```

<img width="1086" alt="Screenshot 2024-07-23 at 8 49 19 AM" src="https://github.com/user-attachments/assets/d5162372-0bdf-499d-a59e-b35faa9bed56">

**Comment by samclassix** [comment]
done
