### ISSUE TITLE
Use normal mouse pointer on positions

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#88]
At the moment, when hovering over a table item, it gets highlighted and the mouse pointer turns into a hand. The hand should only be used for items that you can actually click on. But the highlighting is nice.

![image](https://github.com/user-attachments/assets/a790c818-8a4c-4616-80ae-b19ec5af05ee)

**Comment by luziusmeisser** [comment]
I.e. not this
<img width="110" alt="image" src="https://github.com/user-attachments/assets/bad9d792-6d71-4d53-bad3-8e9980d6d1b9">

but this

![image](https://github.com/user-attachments/assets/eb9c6df5-5d09-4898-a00d-b207595b17e7)

**Comment by samclassix** [comment]
done
