### ISSUE TITLE
Table Item Layout

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#89]
<img width="947" alt="image" src="https://github.com/user-attachments/assets/fa6c08e6-0eaf-48df-9969-e1cbd7de31d7">

We should prevent the name of the collateral to line-wrap. Either it needs to be shortened with an ellipsis (Flocki Master T...) or the column made wider. As a side effect, the additional line also messes with the alignment of the button, which is not vertically centered any more. This should automatically be good again if we restrict the name to one line.

**Comment by samclassix** [comment]
Really fair point. I didnt like the line-wrap. Will adjust it.

**Comment by samclassix** [comment]
done
