### ISSUE TITLE
Page Title Alignment

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#92]
At the moment, the titles on our pages are aligned like this:
![image](https://github.com/user-attachments/assets/e9d796d2-e5de-4f42-8a1e-b9bdd6afd366)

I think we should either left-align (variant 1) or center (variant 2) above the table:
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/902d377c-040b-4bf1-aa05-56f53742ef9f">

My prefernce would be to align left.

**Comment by samclassix** [comment]
Same same. Align Left.

**Comment by samclassix** [comment]
There are pages with titles, and pages without it. When to have and when to remove?

**Comment by luziusmeisser** [comment]
If there are multiple sections, it makes sense to have titles to separate the sections.

For the others, not so much. The governance page and the fps page are particularly ugly as the title is abused as a link. However, since this information is nowhere else, I did not remove them. Let's remove them opportunitistically as we rework those pages. For now, all that needs to be done is the left alignment.

**Comment by samclassix** [comment]
done

**Comment by samclassix** [comment]
<img width="543" alt="Screenshot 2024-08-02 at 5 19 07 PM" src="https://github.com/user-attachments/assets/14ab8739-160e-4641-a085-f817d095aada">
