### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#93]
Can we make the documentation link context aware?

<img width="709" alt="image" src="https://github.com/user-attachments/assets/04bdd3e7-fdbf-432b-8525-a83d77462782">

It should always point to the right subpage in the documentation. For example, in the above screen, the documentation link should point to https://docs.frankencoin.com/positions/auctions

@samclassix : if you don't know what the right page is to link to, please consult @AndreasFC94 .

@AndreasFC94 : if the right documentation page does not exist yet, please create it. Also, please make sure that the documentation page is written in a way that is helpful to the users coming from the frontend. Also, as soon as we have the new design in the frontend, you can add and update a lot of screenshots.

**Comment by samclassix** [comment]
I would adjust the logic in the footer only, and would not link the footer component with other components.
By verifying the "pathname" and adjust the linking behavior, this could be done easily.

**Comment by AndreasFC94** [comment]
I will go through the docs and streamline the text so that it caters to readers coming from the frontend. I'll also create new pages if needed. For example, the monitoring aspects are partially discussed in the challenges and auctions page, but a dedicated docs page might be better. 

I'll also make sure that the docs page is updated once we have the new design.

**Comment by luziusmeisser** [comment]
@AndreasFC94 : can you provide sam a list with the url the footer should point to depending on the path?

For example:
https://app.frankencoin.com/auctions --> https://docs.frankencoin.com/positions/auctions

The match does not need to be perfect, and if there is no match that is better than https://docs.frankencoin.com/, it can also just be https://docs.frankencoin.com/

**Comment by AndreasFC94** [comment]
Yes, here's the list: 

https://app.frankencoin.com/mint --> https://docs.frankencoin.com/positions/open
https://app.frankencoin.com/mypositions --> https://docs.frankencoin.com/positions/adjust
https://app.frankencoin.com/monitoring --> https://docs.frankencoin.com/positions/auctions
https://app.frankencoin.com/auctions --> https://docs.frankencoin.com/positions/auctions
https://app.frankencoin.com/pool --> https://docs.frankencoin.com/pool-shares
https://app.frankencoin.com/governance --> https://docs.frankencoin.com/governance
https://app.frankencoin.com/swap --> https://docs.frankencoin.com/swap

**Comment by samclassix** [comment]
Awesome. 💯 

## Pretty easy to adjust or add new entries
> File: /components/footer.tsx
![Screenshot 2024-08-07 at 9 21 33 AM](https://github.com/user-attachments/assets/4cb65b6c-3c2f-454a-987b-34958ada9dd4)

**Comment by samclassix** [comment]
done. Will keep it open for now, if there are more upcoming dynamic linking... feel free to close if satisfied.
