### ISSUE TITLE
Open auctions page after starting a challenge

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#96]
After successfully launching a challenge, the user still sees this screen:

![image](https://github.com/user-attachments/assets/be56c419-d0bb-412d-a124-7b4fb14089ae)

I think it would be good to have some feedback, ideally, the frontend should navigate to the freshly launched challenge, i.e. the bidding page for the new challenge:

http://localhost:3000/challenges/26/bid

I'm not sure what the best way is to figure out the challenge number. One way could be to simply navigate to the bidding page of the latest challenge after the transaction completed and verifying the owner.

**Comment by samclassix** [comment]
After a Tx, the app will needs a few seconds to update the latest state. The Toaster, i faster then Metamask, Ponder, Api, to recognize the confirmation on the page. Redirecting to a page, which might not yet "exist", could cause in client-side errors and a break in the app. Let me think about this a bit.

**Comment by luziusmeisser** [comment]
@AndreasFC94 : can you provide sam a list with the url the footer should point to depending on the path?

For example:
https://app.frankencoin.com/auctions --> https://docs.frankencoin.com/positions/auctions

The match does not need to be perfect, and if there is no match that is better than  https://docs.frankencoin.com, it can also just be  https://docs.frankencoin.com

**Comment by samclassix** [comment]
1. Does a challenger want to navigate to the challenge bid page after initiating a challenge? 

2. Or does a challenger want to navigate to "MyPositions" where it can find an overview of all owned positions and down below all "owned" initiated challenges? 

<img width="788" alt="Screenshot 2024-08-06 at 10 02 59 AM" src="https://github.com/user-attachments/assets/670347d4-1730-4d3c-b0b1-9d1d2e35679f">

4. Or maybe the position details page? where you can also find all attached challenges of a position.

<img width="1142" alt="Screenshot 2024-08-06 at 10 03 57 AM" src="https://github.com/user-attachments/assets/0dcbc10f-35bb-484d-ac15-8b3598ef0a0d">

**Comment by luziusmeisser** [comment]
I tend to go with the third choice, the position details change.

Ideally, we would also inject some kind of message there, for example: "Newly created challenges will show up as soon as their existence is confirmed by the network."

**Comment by samclassix** [comment]
Considered closed.

- you can **always navigate** to a different page, **while** tx is still pending
- it would cause confusing if you manually navigate away and after the tx you will get auto forwarded to a different page 
- ...
