### ISSUE TITLE
Wrong digits for BOSS in My Positions

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#97]
On my positions, BOSS is shown with the wrong number of digits, i.e. 400.00 instead of 40'000.

![image](https://github.com/user-attachments/assets/7265cbef-0003-4ebd-87d9-02354aeeed3d)

Elsewhere, it is correct:

![image](https://github.com/user-attachments/assets/558dded3-f2db-4e0e-aa37-2d9684779b61)

The example is position 0xed58b9D4f63B3dA63b13078E027C8c3F92D5D597, but it is also wrong for other BOSS positions.

**Comment by samclassix** [comment]
done.
