### ISSUE TITLE
Add owner and position address to challenge page

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#98]
Currently, the challenge page looks like this:

![image](https://github.com/user-attachments/assets/9ceebad2-dcf9-42db-8ac9-10099ee77983)

But maybe one would like to find out which position this concerns and who the owner is, so we should add this information, maybe like this:

<img width="924" alt="image" src="https://github.com/user-attachments/assets/3a0a72cd-04a1-4071-a569-ab5cd2cf0bc4">

So we would remove the second "phase duration" box and rename the first one to "Phase duration". Both phases have the same duration so that is good enough. This allows us to use the second box to point to the target position, for example:

https://app.frankencoin.com/position/0xc724701A14f15888205682c5A192B8baD78353eE

**Comment by samclassix** [comment]
done
