### ISSUE TITLE
Update Position Page

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/frankencoin-dapp#99]
Currently, the position page looks like this:

![image](https://github.com/user-attachments/assets/e37cd577-fa2a-4872-af9f-cced1fb711f2)

We can simplify as follows:

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/de1f0eee-bcbd-49ea-8b53-f2ba00716994">

- Remove the word "overview" from the titel
- Remove the "back to positions" link (instead, the user should be able to use the back button of the browser)
- Remove the button (the actions are supposed to be reached from other places)

**Comment by samclassix** [comment]
<img width="571" alt="Screenshot 2024-08-05 at 10 43 27 AM" src="https://github.com/user-attachments/assets/cc96cc33-6044-4aa3-b2cc-ee1a66cc29a9">

- added external link.
- done
